name: patunai-ir
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - nltk
  - tqdm
  - requests
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - ollama
      - openpyxl
      - transformers
      - accelerate
      - peft
      - bitsandbytes
      - sentence-transformers
      - huggingface-hub
      - google-api-python-client
      - google-auth
      - rank-bm25
      - faiss-cpu
      - rerankers
      - pillow
      - python-dotenv
      - opencv-python
      - timm
      - open-clip-torch
      - jupyterlab
      - ipykernel
      - ipywidgets
      - ipynbname
      - rich
      - typer
